steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=Dockerfile'
      - '--context=.'
      - '--destination=us-central1-docker.pkg.dev/$PROJECT_ID/duckdb/duckdb-server:latest'
      - '--destination=us-central1-docker.pkg.dev/$PROJECT_ID/duckdb/duckdb-server:$SHORT_SHA'
      - '--cache=true'
      - '--cache-ttl=24h'
options:
  machineType: 'E2_HIGHCPU_8'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/duckdb/duckdb-server:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/duckdb/duckdb-server:$SHORT_SHA'
